### ISSUE TITLE
When using return URL, there are multiple issues

### ISSUE THREAD

**Issue by kebetsi** [pryv/app-web-auth2#3]
1. An additional "?" is added (when the documentation tells you to have one already)
2. If you press cancel, the query parameters in the returnURL show status=ACCEPTED & username & pryvToken fields.

**Comment by tmodoux** [comment]
1. Solved in lib-js, the issue was in the returnURL cleaning function, it now checks if a ? is already there
2. Solved in app-web-auth2, instead of returning a hardcoded 'ACCEPTED' (WTF?), it now returns the actual status as well as all others state parameters.
